export const AISidebar = [
  {
    text: 'AI应用开发',
    collapsed: true,
    link: '/ai-tech/application/',
    items: [
      { text: '流式输出', link: '/ai-tech/application/stream' },
      { text: '结构化输出', link: '/ai-tech/application/structured-output' },
      { text: '函数调用', link: '/ai-tech/application/function-calling' },
      { text: '多轮对话实现', link: '/ai-tech/application/chat-history' },
      { text: '上下文管理', link: '/ai-tech/application/context' },
    ],
  },

  {
    text: 'RAG知识库',
    collapsed: true,
    link: '/ai-tech/rag/',
    items: [
      { text: 'RAG介绍', link: '/ai-tech/rag/' },
      { text: 'Embedding原理', link: '/ai-tech/rag/embedding' },
      { text: '向量数据库', link: '/ai-tech/rag/vector-db' },
      { text: '文本切片Chunk', link: '/ai-tech/rag/chunk' },
      { text: '召回策略', link: '/ai-tech/rag/retrieval' },
      { text: '重排序Rerank', link: '/ai-tech/rag/rerank' },
      { text: '混合检索', link: '/ai-tech/rag/hybrid-search' },
      { text: '知识库实战', link: '/ai-tech/rag/project' },
    ],
  },
  {
    text: 'Agent开发',
    collapsed: true,
    link: '/ai-tech/agent/',
    items: [
      { text: 'Agent介绍', link: '/ai-tech/agent/' },
      { text: 'Agent架构', link: '/ai-tech/agent/architecture' },
      { text: 'Tool Calling', link: '/ai-tech/agent/tool-calling' },
      { text: 'Memory机制', link: '/ai-tech/agent/memory' },
      { text: 'Planning规划', link: '/ai-tech/agent/planning' },
      { text: 'ReAct模式', link: '/ai-tech/agent/react' },
      { text: 'Multi-Agent', link: '/ai-tech/agent/multi-agent' },
      { text: 'Agent实战项目', link: '/ai-tech/agent/project' },
    ],
  },
  // {
  //   text: 'MCP开发',
  //   collapsed: true,
  //   link: '/ai-tech/mcp/',
  //   items: [
  //     { text: 'MCP介绍', link: '/ai-tech/mcp/' },
  //     { text: 'MCP协议原理', link: '/ai-tech/mcp/protocol' },
  //     { text: 'MCP Server开发', link: '/ai-tech/mcp/server' },
  //     { text: 'MCP Client开发', link: '/ai-tech/mcp/client' },
  //     { text: 'Tool注册机制', link: '/ai-tech/mcp/tool' },
  //     { text: 'MCP实战案例', link: '/ai-tech/mcp/project' },
  //   ],
  // },
  // {
  //   text: 'AI前端开发',
  //   collapsed: true,
  //   link: '/ai-tech/frontend/',
  //   items: [
  //     { text: 'AI聊天应用开发', link: '/ai-tech/frontend/chat' },
  //     { text: 'SSE流式输出', link: '/ai-tech/frontend/sse' },
  //     { text: 'WebSocket通信', link: '/ai-tech/frontend/websocket' },
  //     { text: 'Markdown渲染', link: '/ai-tech/frontend/markdown' },
  //     { text: '代码高亮', link: '/ai-tech/frontend/highlight' },
  //     { text: '打字机效果', link: '/ai-tech/frontend/typewriter' },
  //     { text: '文件上传解析', link: '/ai-tech/frontend/upload' },
  //     { text: 'AI工作流界面', link: '/ai-tech/frontend/workflow' },
  //   ],
  // },
  // {
  //   text: 'AI工程化',
  //   collapsed: true,
  //   link: '/ai-tech/engineering/',
  //   items: [
  //     { text: 'AI项目架构', link: '/ai-tech/engineering/' },
  //     { text: 'Prompt管理', link: '/ai-tech/engineering/prompt-management' },
  //     { text: '模型路由', link: '/ai-tech/engineering/model-router' },
  //     { text: '缓存策略', link: '/ai-tech/engineering/cache' },
  //     { text: '限流与熔断', link: '/ai-tech/engineering/rate-limit' },
  //     { text: '监控与日志', link: '/ai-tech/engineering/monitor' },
  //     { text: '成本优化', link: '/ai-tech/engineering/cost' },
  //     { text: 'AI安全防护', link: '/ai-tech/engineering/security' },
  //   ],
  // },
]
